random_seed: 19
device:
  type: cuda
  ordinal: 0
dataset_dir: './dataset/part2bertcased'
data_loader:
  max_sent_len: 64
  max_word_len: 16
  batch_size: 6
  n_workers: 0
net:
  char_conv_kernel_size: 3
  d_model: 128
  dropout: 0.1
use_elmo: false
elmo_embedder:
  # Set the value of ``ELMo.embedder`` init parameters here.
  n_ctx_embs: 24  # The number of the contextualized embedding, required.
  ctx_emb_dim: 1024  # The dimension of the contextualized embedding, required.
optim:
  algo: 'Adam'
  kwargs:
    lr: 1.0e-5
train:
  n_epochs: 40
  max_grad_norm: 1
  n_gradient_accumulation_steps: 1  # Must be a divider of data_loader.batch_size.
